version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo Installing Python dependencies...
      - pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo Pre-build step...
      - ls -la

  build:
    commands:
      - echo Zipping project...
      - zip -r flask-app.zip * .[^.]*

artifacts:
  files:
    - flask-app.zip
